### ISSUE TITLE
Improve the recognition

### ISSUE THREAD

**Issue by MAPReiff** [coehler/Anime-Auditor#1]
Don't know if this is something that can be done on your end (aka being the bot guy), but the bot flagged people for anime that were clearly not and claimed many people who had anime pictures were said to not.
![image](https://user-images.githubusercontent.com/7242589/80854487-c883e180-8c06-11ea-9dc6-61dab1082f11.png)

**Comment by coehler** [comment]
Yeah, its definitely not perfect. In my experience its got a 20 to 30 percent false negative rate and a similar false positive rate. It all sort of hinges on the performance of the Haar cascade file (which I didn't make) that defines what is and isn't Anime.

What you can do is tweak the parameters passed to the ``detectMultiScale`` call on line 384.

For example, altering the values such that ``minNeighbors = 3`` will result in a lower false positive rate but might also lead to a higher false negative rate.

You can read more about the other parameters [here](https://docs.opencv.org/2.4/modules/objdetect/doc/cascade_classification.html#cascadeclassifier-detectmultiscale) on the OpenCV docs page.

Hope this helped.
